#!/bin/bash

WORKDIR=${PWD}

source "$WORKDIR"/docker/.env

case $1 in
    "$SK3_APPLICATION_NAME")
        DOMAIN=$SK3_APPLICATION_DOMAIN
        DATABASE_NAME=$SK3_MARIADB_DATABASE_NAME
        ;;
    "$VIPDATE_APPLICATION_NAME")
        DOMAIN=$VIPDATE_APPLICATION_DOMAIN
        DATABASE_NAME=$VIPDATE_MARIADB_DATABASE_NAME
        ;;
    "$F4C_APPLICATION_NAME")
        DOMAIN=$F4C_APPLICATION_DOMAIN
        DATABASE_NAME=$F4C_MARIADB_DATABASE_NAME
        ;;
    *)
        ;;
esac
